Multiple Metrics
Capstone2401/frontend-app pull request #16
Opened 2024-05-08 19:00 UTC by brandoncorey

In this PR, the ability to add multiple queries to the dashboard is added. Fundamentally, the core state is more dynamic, with query being held in an object within an array, rather than hardcoded as single selections.

There is one area that may potentially be an issue, where I use an index as the key in a react component. It does not cause problems currently, but maybe can be replaced?

2024-05-08 19:13 UTC, AlliLearns commented on src/components/Dropdown.jsx
Please add a clarifying comment about the possible value(s) of `items`.

2024-05-08 19:30 UTC, AlliLearns commented on src/components/FilterDropdownOptions.jsx
Suggested change: rename `value` to `attrValue` or `attributeValue`.

2024-05-08 19:36 UTC, AlliLearns commented on src/components/QueryBuilder.jsx
Update `setQuery` to `setQueryState`

2024-05-08 20:03 UTC, AlliLearns commented on src/components/ResultGraph.jsx
Grab first element of `queryData` array on line 94 and turn `queryData[0].aggregationType` into a variable.

2024-05-08 20:07 UTC, AlliLearns requested changes
Thanks! See comments for updates.

2024-05-09 04:41 UTC, brandoncorey commented on src/components/Dropdown.jsx
changed to `availableOptions`

2024-05-09 04:41 UTC, brandoncorey commented on src/components/FilterDropdownOptions.jsx
changed to `attrValue`

2024-05-09 04:41 UTC, brandoncorey commented on src/components/ResultGraph.jsx
done

2024-05-09 04:48 UTC, brandoncorey commented
The most substantial change is the UUID for the queries, I switched `queryState` to an object with the UUIDs as the key, but because before it was just an array being accessed with an index, the syntax didn't need to change for almost any of the code. Only when making the requests to the backend is there a slight change.

2024-05-09 15:17 UTC, AlliLearns reviewed
Great, looks good! Thanks!

2024-05-09 15:17 UTC, merged